[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.64.0"
HUGO_ENV = "production"
RUBY_VERSION = "2.6.2"

[context.deploy-preview.environment]
HUGO_VERSION = "0.64.0"
RUBY_VERSION = "2.6.2"
